---
title: "Discussion section activity"
format: html
editor_options: 
  chunk_output_type: console
---

### Load libraries
```{r}
library(here)
library(tidyverse)
library(sf)
library(tmap)
```

#### Import data
```{r}
sb_protected_areas <- read_sf(here::here("data", "cpad_super_units_sb.shp")) %>% 
  st_transform("ESRI:102009")

sb_city_boundaries <- read_sf(here::here("data", "sb_city_boundaries_2003.shp")) %>%
  st_transform("ESRI:102009")

sb_county_boundary <- read_sf(here::here("data", "sb_county_boundary_2020.shp")) %>%
  st_transform("ESRI:102009")

aves <- read_sf(here::here("data", "aves_observations_2020_2024.shp")) %>%
  st_transform("ESRI:102009")
```

#### Tasks

1. Find how many bird observations are within protected areas in Santa Barbara County

```{r}
# Bracket subsetting method
aves_pa_subset <- sb_protected_areas[aves, ]

# Check no. observations
nrow(aves_pa_subset)

# Take a look
tm_shape(sb_protected_areas) +
  tm_polygons() +
  tm_shape(aves_pa_subset) +
  tm_dots()
```


```{r}
# Spatial join method - Append the Protected Area geometries to the bird observation geometries
aves_PA_join <- st_join(aves, sb_protected_areas)

tm_shape(sb_county_boundary) +
  tm_fill() +
  tm_shape(sb_protected_areas) +
    tm_borders(lwd = 1, col = "#fb8500") +
    tm_fill(col = "#fb8500", alpha = 0.2) +
  tm_shape(aves_PA_join) +
    tm_dots(col = "#023047") +
  tm_layout(main.title = "Birds in Santa Barbara\nCounty Protected Areas",
            main.title.size = 1)
```

And try adding a 5 km buffer around the protected areas:
```{r}
# Check if units are in meters
st_crs(sb_protected_areas)$units

# Create 5000m buffer around PAs
PA_buffer_5km <- st_buffer(sb_protected_areas, dist = 5000)

# Subset the buffered PA geoms to only those with bird observations
aves_buffer_subset <- PA_buffer_5km[aves, ]

tm_shape(sb_county_boundary) +
  tm_fill() +
  tm_shape(sb_protected_areas) +
    tm_borders(lwd = 1, col = "#fb8500") +
    tm_fill(col = "#fb8500", alpha = 0.2) +
  tm_shape(aves_buffer_subset) +
  tm_dots(col = "#023047") +
  tm_layout(main.title = "Birds in Santa Barbara\nCounty Protected Areas",
            main.title.size = 1)

nrow(aves_buffer_subset)
```

2. Find the protected areas within 15 km of Goleta
```{r}
# Filter to Goleta
goleta <- sb_city_boundaries |>
  filter(NAME == "Goleta")

# Create 15km buffer around Goleta
st_crs(goleta)$units
goleta_buffer_15km <- st_buffer(goleta, dist = 15000)

# Explore the different outputs with different spatial operations
goleta_PAs_within <- st_within(sb_protected_areas, goleta_buffer_15km)
goleta_PAs_intersect <- st_intersects(sb_protected_areas, goleta_buffer_15km)
goleta_PAs_intersection <- st_intersection(sb_protected_areas, goleta_buffer_15km)

# Compute distance-based join
goleta_PAs_join <- st_join(sb_protected_areas, goleta, st_is_within_distance, dist = 15000)

tm_shape(goleta_PAs_join) +
  tm_polygons()

```



3. Find the distance between your city of choice and a protected area of your choice




